### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by debiprasadmishra50** [Kashishkashyap/FlightBookingSite#1]
homework.js

The solution although works, is not scalable and there is a better way to do it. 
The method that you have will not require Promises even
But the solution must use promise and it would give you a scalable solution. 

Try again

**Comment by Kashishkashyap** [comment]
> homework.js
> 
> The solution although works, is not scalable and there is a better way to do it. The method that you have will not require Promises even But the solution must use promise and it would give you a scalable solution.
> 
> Try again

Hello sir, 

As per the feedback, I’ve tried to rewrite my homework code to make it more scalable and have used Promises effectively. I’ve also added proper comments to explain my approach.
Let me know if there are any other improvements I can make. Thank you for your time and guidance!

**Comment by debiprasadmishra50** [comment]
```TS
const wait = async (secs: number) => new Promise<void>((resolve) => setTimeout(resolve, secs * 1000));

const run = async () => {
  console.log("[+] Starting Application...");
  const runTimes = 5,
    waitSecs = 2;

  for (let i = 1; i <= runTimes; i++) {
    await wait(waitSecs);
    console.log(`[+] ${i * waitSecs} Secs has passed`);
  }

  console.log("[+] Ending Application...");
};

run().catch(console.error);
```

Here is the actual code
readable, re-usable, scalable, used promises efficiently

**Comment by debiprasadmishra50** [comment]
readable, re-usable, scalable, used promises efficiently

**Comment by Kashishkashyap** [comment]
Thank you for providing the solution. I have reviewed it, and it indeed makes the code more readable, re-usable, scalable, and efficient in using Promises.

**Comment by Kashishkashyap** [comment]
Thank you for providing the solution. I have reviewed it, and it indeed makes the code more readable, re-usable, scalable, and efficient in using Promises.
Thank you for your help.
